### ISSUE TITLE
Shipment id is not being generated when creating Shipment object

### ISSUE THREAD

**Issue by pskramtai** [yjhn/shipping-service#10]
When adding a new shipment through ShipmentRegistration page, shipment id has to be arbitrarily set to some value, otherwise it will be null. I assume the same problem applies to other entities.

**Comment by EvalVis** [comment]
This was the issue. But wasn't it fixed? I mentioned it in #7 and @yjhn should have fixed it. Maybe it was not fully patched and some essential statement is missing.

**Comment by EvalVis** [comment]
This commit a6e602ba78e7b6f58e51339edf91496b7691c6bc should have dealth with it.

**Comment by EvalVis** [comment]
@pskramtai Could you push a code to the repo?

**Comment by EvalVis** [comment]
Also, this could help: https://stackoverflow.com/questions/54240063/valuegeneratedonadd-has-no-effect.
Maybe Ids are not 0 then pushed to the db?

**Comment by pskramtai** [comment]
> @pskramtai Could you push a code to the repo?

The code is here
https://github.com/yjhn/shipping-service/blob/shipment-registration-frontend/Pages/Shipment/ShipmentRegistration.razor

**Comment by pskramtai** [comment]
> 

Here is the exception:

> PostgresException: 23502: null value in column "Id" of relation "Shipments" violates not-null constraint

**Comment by EvalVis** [comment]
Yeah, seen that one. This one was requested to be fixed.

**Comment by EvalVis** [comment]
Removed manual Id insertion in SeedData.cs so we can make sure this issue is gone (then it is) at the start of program.

**Comment by EvalVis** [comment]
I have no idea how to fix this yet. Hopefully @yjhn can fix this tomorrow.

**Comment by EvalVis** [comment]
@yjhn Tried to check this at db level: INSERT INTO public."PostMachines" ("Name", "Address") VALUES ('Test', 'Testas') fails. So maybe solve this issue at db level?

**Comment by vleveris** [comment]
Made a commit regarding ID columns generation strategy (it seems there is a problem with PGSQL ID generation using EF). Couldn't check if it is fully fixed because on shipment registration I got InvalidOperationException (but hopefully it is not linked with ID auto generation).

**Comment by EvalVis** [comment]
This caused a new exception: System.ArgumentException: 'Identity value generation cannot be used for the property 'Id' on entity type 'shipping_service.Persistence.Entities.Courier (Dictionary<string, object>)' because the property type is 'decimal'. Identity columns can only be of type short, int or long.'

**Comment by EvalVis** [comment]
@vleveris Can you elaborate on InvalidOperationException, what causes it and when it happens?

**Comment by pskramtai** [comment]
> Made a commit regarding ID columns generation strategy (it seems there is a problem with PGSQL ID generation using EF). Couldn't check if it is fully fixed because on shipment registration I got InvalidOperationException (but hopefully it is not linked with ID auto generation).

I assume this is related to this issue: https://github.com/yjhn/shipping-service/issues/11. It has not been resolved yet. You can try converting IEnumerable<PostMachine> to list for now.

**Comment by EvalVis** [comment]
Maybe ulong type is not allowed?

**Comment by vleveris** [comment]
In order to start after this commit, perhaps you need to drop database and recreate it, or remove two latest migration files.

**Comment by EvalVis** [comment]
Maybe. Probably, since the issue is at the db level.

**Comment by vleveris** [comment]
> > Made a commit regarding ID columns generation strategy (it seems there is a problem with PGSQL ID generation using EF). Couldn't check if it is fully fixed because on shipment registration I got InvalidOperationException (but hopefully it is not linked with ID auto generation).
> 
> I assume this is related to this issue: #11. It has not been resolved yet. You can try converting IEnumerable to list for now.

When I click on Shipment->Register a Shipment and fill in form, an exception appears saying "System.InvalidOperationException: 'A second operation was started on this context instance before a previous operation completed."

**Comment by EvalVis** [comment]
Yep, that's the #11 issue.

**Comment by EvalVis** [comment]
However, the solution has been proposed. Marking .razor with @inherits OwningComponentBase after @page line and calling postMachine repository with public IPostMachineRepository PostMachineRepository => Service; would also help.

**Comment by vleveris** [comment]
So that's why I'm not sure if this solution with ID generation works.

**Comment by EvalVis** [comment]
Using List is not advised since Blazor should be dynamic.

**Comment by EvalVis** [comment]
OK, I will push the changes and close the #11 issue, wait a minute or two.

**Comment by EvalVis** [comment]
@vleveris Do you get the exception I mentioned now:

> This caused a new exception: System.ArgumentException: 'Identity value generation cannot be used for the property 'Id' on entity type 'shipping_service.Persistence.Entities.Courier (Dictionary<string, object>)' because the property type is 'decimal'. Identity columns can only be of type short, int or long.'

**Comment by yjhn** [comment]
I created a PR that should fix this issue.
