### ISSUE TITLE
Invalid operation exception related to DbContext when using Picker element

### ISSUE THREAD

**Issue by pskramtai** [yjhn/shipping-service#11]
When submit button of shipment registration form is clicked, this exception is thrown.

> System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913

If the Picker element is removed, the exception will not be thrown.

https://go.microsoft.com/fwlink/?linkid=2097913 suggests adding DbContextFactory.

Link to code:
https://github.com/yjhn/shipping-service/blob/shipment-registration-frontend/Pages/Shipment/ShipmentRegistration.razor

**Comment by pskramtai** [comment]
https://docs.microsoft.com/lt-lt/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor.
This section provides more information about blazor in relation to DbContext

**Comment by EvalVis** [comment]
This is strange. I have seen it and it points to PostMachines at crash time. But PostMachines is specifically set to IEnumerable not IQuerable, so IDK why this occurs.

**Comment by EvalVis** [comment]
setting IEnumerable<PostMachine> to List<PostMachine> solves it but it should work with IEnumerable, no idea why it fails.

**Comment by EvalVis** [comment]
Marking .razor with @inherits OwningComponentBase<IPostMachineRepository>
after @page line
and calling postMachine repository with public IPostMachineRepository PostMachineRepository => Service; would also help.

**Comment by EvalVis** [comment]
But probably after shipment creation a redirection is needed, because why stay on shipment creation page? Unless you have multiple shipments to deliver.

**Comment by EvalVis** [comment]
Maybe this also could be a solution: https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-6.0

**Comment by EvalVis** [comment]
> Marking .razor with @inherits OwningComponentBase after @page line and calling postMachine repository with public IPostMachineRepository PostMachineRepository => Service; would also help.

Did this solve the issue?

**Comment by EvalVis** [comment]
Pushed a commit about this:

> Marking .razor with @inherits OwningComponentBase after @page line and calling postMachine repository with public IPostMachineRepository PostMachineRepository => Service; would also help.

Should have resolved the issue.
